name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]   # se ejecuta automáticamente al hacer push en main
  workflow_dispatch:       # también lo podés lanzar manualmente
    inputs:
      tag:
        description: "Tag de la imagen (ej: latest, dev, v1.0)"
        required: true
        default: "latest"
      push_image:
        description: "¿Subir la imagen a Docker Hub?"
        required: true
        default: "false"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Limpiar espacio en runner
      run: |
    docker system prune -af
    docker volume prune -f

      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Verificar Dockerfile en raíz
        run: ls -l

      - name: Build de la imagen
        run: docker build -t tomillo037/tomexarch:${{ github.event.inputs.tag }} .

      - name: Test de la imagen
        run: docker run --rm tomillo037/tomexarch:${{ github.event.inputs.tag }} echo "Imagen construida correctamente"

      - name: Push a Docker Hub
        if: ${{ github.event.inputs.push_image == 'true' }}
        run: docker push tomillo037/tomexarch:${{ github.event.inputs.tag }}
