name: Build and Push Docker Image

on:
  workflow_dispatch:   # Permite lanzarlo manualmente desde GitHub
    inputs:
      tag:
        description: "Tag de la imagen (ej: latest, dev, v1.0)"
        required: true
        default: "latest"
      push_image:
        description: "Â¿Subir la imagen a Docker Hub?"
        required: true
        default: "false"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

    - name: Verificar Dockerfile
      run: ls -l

      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build de la imagen
        run: docker build -t tomillo037/tomexarch:${{ github.event.inputs.tag }} .

      - name: Test de la imagen
        run: docker run --rm tomillo037/tomexarch:${{ github.event.inputs.tag }} echo "Imagen construida correctamente"

      - name: Push a Docker Hub
        if: ${{ github.event.inputs.push_image == 'true' }}
        run: docker push tomillo037/tomexarch:${{ github.event.inputs.tag }}
